- hosts: web
  vars_files:
    - ../vars/users.yml
  tasks:
  - name: Add user
    ansible.builtin.user:
      name: "{{ user_name }}"
      password:  "{{ user_password | password_hash('sha512') }}"
      state: present

  - name: Add user to sudo group
    user:
      name: "{{ user_name}}"
      groups: sudo
      append: yes
    become: yes

  - name: Add user to docker group
    user:
      name: "{{ user_name}}"
      groups: docker
      append: yes
    become: yes