version: '3.1'
services:
  nginx:
      container_name: nginx-min
      image: nginx
      ports:
        - "8080:80"
      restart: always
      volumes:
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./../www:/www:cached

  php:
    container_name: php-min
    build: .
    restart: always
    volumes:
      - ./../www:/www